language: php
os: linux
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
php:
- 8.0

before_install: 
- pecl install pcov

install:
- composer install

before_script:
    - wget https://github.com/infection/infection/releases/download/0.24.0/infection.phar
    - chmod +x infection.phar

script:
- vendor/bin/phpunit tests
- ./infection.phar --min-msi=48 --min-covered-msi=70 --threads=4
